//[Document Untitled-2]
a =
{
    stationery: false,
    fullName: " /d/ % D7 % AA % D7 % 95 % D7 % 9B % D7 % A0 % D7 % 95 % D7 % AA /% D7 % AA % D7 % 95 % D7 % 9B % D7 % A0 % D7 % 95 % D7 % AA % 20 % D7 % A9 % D7 % 9E % D7 % 95 % D7 % AA % D7 % A7 % D7 % A0 % D7 % 95 % D7 % AA / Adobe % 20Illustrator % 20CC % 202015 / Support % 20Files / Contents / Windows / Untitled - 2,",
    // activeLayer: //[Layer Layer 1]
    //     {
    //         visible: true,
    //             locked: false,
    //                 printable: true,
    //                     hasSelectedArtwork: true,
    //                         preview: true,
    //                             dimPlacedImages: false,
    //                                 color: //[RGBColor]
    // //         {
    // //             red: 78.6926070038911,
    // //                 green: 127.501945525292,
    // //                     blue: 255,
    // //                         typename: "RGBColor",
    // // },
    //         name: "Layer 1",
    //             opacity: 100,
    //                 zOrderPosition: 1,
    //                     absoluteZOrderPosition: 3,
    //                         sliced: false,
    //                             blendingMode: BlendModes.NORMAL,
    //                                 isIsolated: false,
    //                                     artworkKnockout: KnockoutState.INHERITED,
    //                                         typename: "Layer",
    //                                             parent: "[Document Untitled-2]",
    //                                                 layers: //[Layers]
    //         {
    //             length: 0,
    //                 parent: "[Layer Layer 1]",
    //                     length: 0,
    //                         typename: "Layers",
    // },
    //     },
    activeView: //[View]
    {
        bounds: [-190.5, 51, 641.5, -388],
        centerPoint: [225.5, -168.5],
        zoom: 2,
        screenMode: ScreenMode.MULTIWINDOW,
        typename: "View",
        parent: "[Document Untitled-2]",
    },
    geometricBounds: [30.5, -20.4591836929321, 261.566607267174, -223.5],
    visibleBounds: [30.5, -20.4591836929321, 261.566607267174, -223.5],
    rulerOrigin: [0, 270.959183673469],
    rulerUnits: RulerUnits.Millimeters,
    pageOrigin: [-8, -817],
    cropBox: [0, 0, 290.836734693878, -270.959183673469],
    cropStyle: CropOptions.Standard,
    width: 290.836734693878,
    height: 270.959183673469,
    showPlacedImages: false,
    outputResolution: 800,
    printTiles: false,
    // selection: [
    //     //[PathItem ]
    //     {
    //         closed: true,
    //         area: 44276.3671875,
    //         length: 842.21484375,
    //         guides: false,
    //         filled: true,
    //         fillColor: //[CMYKColor]
    //         {
    //             cyan: 12.9427015781403,
    //             magenta: 74.9843537807465,
    //             yellow: 100,
    //             black: 2.56961919367313,
    //             typename: "CMYKColor",
    //         },
    //         fillOverprint: false,
    //         stroked: false,
    //         strokeColor: //[NoColor]
    //         {
    //             typename: "NoColor",
    //         },
    //         strokeOverprint: false,
    //         strokeWidth: 1,
    //         strokeDashes: [],
    //         strokeDashOffset: 0,
    //         strokeCap: StrokeCap.BUTTENDCAP,
    //         strokeJoin: StrokeJoin.MITERENDJOIN,
    //         strokeMiterLimit: 10,
    //         clipping: false,
    //         evenodd: false,
    //         resolution: 800,
    //         selectedPathPoints: [
    //             //[PathPoint]
    //             {
    //                 anchor: [261.566607267174, -223.5],
    //                 leftDirection: [261.566607267174, -223.5],
    //                 rightDirection: [261.566607267174, -223.5],
    //                 pointType: PointType.CORNER,
    //                 selected: PathPointSelection.ANCHORPOINT,
    //                 typename: "PathPoint",
    //                 parent: "[PathItem ]",
    //             },
    //             //[PathPoint]
    //             {
    //                 anchor: [43.5, -223.5],
    //                 leftDirection: [43.5, -223.5],
    //                 rightDirection: [43.5, -223.5],
    //                 pointType: PointType.CORNER,
    //                 selected: PathPointSelection.ANCHORPOINT,
    //                 typename: "PathPoint",
    //                 parent: "[PathItem ]",
    //             },
    //             //[PathPoint]
    //             {
    //                 anchor: [43.5, -20.4591836929321],
    //                 leftDirection: [43.5, -20.4591836929321],
    //                 rightDirection: [43.5, -20.4591836929321],
    //                 pointType: PointType.CORNER,
    //                 selected: PathPointSelection.ANCHORPOINT,
    //                 typename: "PathPoint",
    //                 parent: "[PathItem ]",
    //             },
    //             //[PathPoint]
    //             {
    //                 anchor: [261.566607267174, -20.4591836929321],
    //                 leftDirection: [261.566607267174, -20.4591836929321],
    //                 rightDirection: [261.566607267174, -20.4591836929321],
    //                 pointType: PointType.CORNER,
    //                 selected: PathPointSelection.ANCHORPOINT,
    //                 typename: "PathPoint",
    //                 parent: "[PathItem ]",
    //             },
    //         ],
    //         polarity: PolarityValues.POSITIVE,
    //         typename: "PathItem",
    //         uRL: "",
    //         note: "",
    //         layer: //[Layer Layer 1]
    //         {
    //             visible: true,
    //             locked: false,
    //             printable: true,
    //             hasSelectedArtwork: true,
    //             preview: true,
    //             dimPlacedImages: false,
    //             color: //[RGBColor]
    //             {
    //                 red: 78.6926070038911,
    //                 green: 127.501945525292,
    //                 blue: 255,
    //                 typename: "RGBColor",
    //             },
    //             name: "Layer 1",
    //             opacity: 100,
    //             zOrderPosition: 1,
    //             absoluteZOrderPosition: 3,
    //             sliced: false,
    //             blendingMode: BlendModes.NORMAL,
    //             isIsolated: false,
    //             artworkKnockout: KnockoutState.INHERITED,
    //             typename: "Layer",
    //             parent: "[Document Untitled-2]",
    //             layers: //[Layers]
    //             {
    //                 length: 0,
    //                 parent: "[Layer Layer 1]",
    //                 length: 0,
    //                 typename: "Layers",
    //             },
    //         },
    //         locked: false,
    //         hidden: false,
    //         selected: true,
    //         position: [43.5, -20.4591836929321],
    //         width: 218.066607267174,
    //         height: 203.040816307068,
    //         geometricBounds: [43.5, -20.4591836929321, 261.566607267174, -223.5],
    //         visibleBounds: [43.5, -20.4591836929321, 261.566607267174, -223.5],
    //         controlBounds: [43.5, -20.4591836929321, 261.566607267174, -223.5],
    //         name: "",
    //         blendingMode: BlendModes.NORMAL,
    //         opacity: 100,
    //         isIsolated: false,
    //         artworkKnockout: KnockoutState.DISABLED,
    //         zOrderPosition: 1,
    //         absoluteZOrderPosition: 1,
    //         editable: true,
    //         sliced: false,
    //         top: -20.4591836929321,
    //         left: 43.5,
    //     },
    // ],
    splitLongPaths: false,
    tileFullPages: false,
    useDefaultScreen: true,
    documentColorSpace: DocumentColorSpace.CMYK,
    name: "Untitled-2",
    // path: ,
    saved: false,
    defaultFilled: true,
    // defaultFillColor: //[CMYKColor]
    // {
    //     cyan: 12.9427015781403,
    //     magenta: 74.9843537807465,
    //     yellow: 100,
    //     black: 2.56961919367313,
    //     typename: "CMYKColor",
    // },
    defaultFillOverprint: false,
    defaultStroked: false,
    defaultStrokeColor: //[NoColor]
    {
        typename: "NoColor",
    },
    defaultStrokeOverprint: false,
    defaultStrokeWidth: 1,
    defaultStrokeDashes: [],
    defaultStrokeDashOffset: 0,
    defaultStrokeCap: StrokeCap.BUTTENDCAP,
    defaultStrokeJoin: StrokeJoin.MITERENDJOIN,
    defaultStrokeMiterLimit: 10,
};
